---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
sum(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}
class(studentMajors)
```

```{r}
studentMajors0 <- c ("eco","eco","law")
```
```{r}
class(studentMajors0)
```

```{r}
typeof(studentMajors)
```

```{r}
typeof(studentMajors0)
```

```{r}
levels(studentMajors)
```

```{r}
as.integer(studentMajors)
```
```{r}
studentMajors
```

```{r}
birthplace <- factor(c("台北市","台北市","台中市","台南市","高雄市"))
```

```{r}
levels(birthplace)
```

```{r}
as.integer(birthplace)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) 
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) 
```

```{r}
library(lubridate)
```

```{r}
dtObject <- ymd_hms("1970-01-01 00:02:53")
```

```{r}
dtObjectVector <- ymd_hms(c("1970-01-01 00:02:53","1980-02-11 11:25:22"))
```

```{r}
class(dtObject)
```

```{r}
class(dtObjectVector)
```

```{r}
typeof(dtObject)
typeof(dtObjectVector)
```

```{r}
as.double(dtObject)
as.double(dtObjectVector)
as.integer(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-20 17:01:00", tz="Asia/Taipei")
```

```{r}
typeof(twDateTime)
```

```{r}
as.double(twDateTime)
```

