---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```

```{r}
currency <- as.factor(currency)
```

```{r}
class(currency)
```
```{r}
levels(currency)
```

```{r}
head(currency)
```

```{r}
length(levels(currency))
```

```{r}
step1_extractLevelsVector <- levels(currency)
step1_extractLevelsVector
```

```{r}
step2_countVectorLength <- length(step1_extractLevelsVector)
step2_countVectorLength
```

```{r}
head(currency)
```

```{r}
currency2 <- c("日圓","美元","日圓")
currency2
```

```{r}
currency2 == "日圓"
sum(currency2 =="日圓")
```

```{r}
head(currency)
sum(currency == "日圓JPY/USD")
```

#5.4
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```

```{r}
(x5 %in% greatTaipei) & (y5=="女")
```

```{r}
(x5 %in% greatTaipei) | (y5=="女")
```

```{r}
xor(x5 %in% greatTaipei, y5=="女")
```

```{r}
y5
(y5 == "女")
which(y5=="女")
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```
```{r}
class(date)
```
```{r}
head(date)
```
```{r}
library(lubridate)
date <- ymd(date)
class(date)
date
```
```{r}
isAfter19800801 <- date >= ymd("1980-08-01")
isAfter19800801
```
```{r}
head(as.integer(date))
as.integer(ymd("1980-08-01"))
head(date >= ymd("1980-08-01"))
```

```{r}
class(isAfter19800801)
```

```{r}
sum(isAfter19800801)
```
```{r}
head(currency)
```


```{r}
head(currency == "歐元USD/EUR")
isEuro <- currency == "歐元USD/EUR"
```

```{r}
sum(isEuro)
```
```{r}
currency <- as.factor(currency)
```

```{r}
isEuro <- currency == "歐元USD/EUR"
sum(isEuro)
```
```{r}
isExchangeRateNA <- is.na(exchangeRate)
sum(isExchangeRateNA)
```

```{r}
isNotNA <- !is.na(exchangeRate)
isEuro <- currency == "歐元USD/EUR"
satisfyBoth <- isNotNA & isEuro
sum(satisfyBoth)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```

```{r}
sum(major == "經濟學系")
```

```{r}
sum(studentID == "5bdS6977b")
```

```{r}
sum(studentID == "5bdS6977b" & grade >= 60)
```

```{r}
sum(major == "經濟學系" & courseType == "選")
```

```{r}
sum(major == "經濟學系" & courseType == "必") -> a
a
```

```{r}
sum(major == "經濟學系" & courseType == "必" & grade < 60) -> b
b
```
```{r}
b/a
```

