---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)

now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
now2()
```

```{r}
textbookURL <- function(){
browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#returninput")}
textbookURL()
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```

```{r}
supply_fun <-  function(a,b,P){
  Qs<- a+b*P
  return(Qs)
}
demand_fun <- function(c,d,P){
  Qd<- c-d*P
  return(Qd)
}
demand_supply_fun <- function(P,a,b,c,d){
  Qs <- a+b*P
  Qd <- c-d*P
  return(list(供給量=Qs,需求量=Qd,超額供給量=Qs-Qd))
}
demand_supply_fun(2,3,4,5,6)
```


```{r}
#method1
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```

```{r}
#範例5
a<-0
b<-1
supply_fun <- function(P,a,b){
  Qs <- a+b*P
  return(Qs)
}
supply_fun(P=-1,0,1)
```

```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs)
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```

```{r}
#method2
a <-  readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
} else {
  print("a不為負值")
}
```

```{r}
#範例6
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P can't be negative") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```


```{r}
#範例2
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
#範例6 green
gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  subSample <- transcriptDataFinal[logiChosenStudent,]
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
  }
  else
    {
      message("can't find this studentID")
    }
}

gpa_fun("92aS67fee")
gpa_fun("aa829838s")
```

```{r}
#method3
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```

```{r}
#範例7
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P can't be negative") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P should greater than or equal to ",-a/b,"(value: -a/b)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
#範例7 green:Implement a fizzbuzz function. It takes a single number as input. If the number is divisible by three, it returns “fizz”. If it’s divisible by five it returns “buzz”. If it’s divisible by three and five, it returns “fizzbuzz”. Otherwise, it returns the number. Make sure you first write working code before you create the function. –From, R for Data Science.
fizzbuzzfun <- function(x){
  if(x %% 3 ==0){
    return("fizz")
  }
  else if(x %% 5 ==0){
    return("buzz")
  }
  else if(x %% 15 ==0){
    return("fizzbuzz")
  }
  else{
    return(x)
  }
}
fizzbuzzfun(3)
fizzbuzzfun(5)
fizzbuzzfun(30)
fizzbuzzfun(22)
```

```{r}
FizzbuzzFun <- function(fizzbuzz){
 if(fizzbuzz %% 15 ==0){
  return("fizzbuzz")
}
else if(fizzbuzz %% 5 ==0){
  return("buzz")
}
else if(fizzbuzz %% 3 ==0){
  return("fizz")
}
else{
  return(fizzbuzz)
} 
}

FizzbuzzFun(3)
FizzbuzzFun(5)
FizzbuzzFun(15)
FizzbuzzFun(4)
```

