---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- 5
a2 <- 5L
class(a)
class(a2)
aVector<-c(5,6,7)
a2Vector<-c(5L,6L,7L)
class(aVector)
class(a2Vector)
```


```{r}
b<-"你好"
bVector<-c("你好","How are you?")
class(b)
class(bVector)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
sum(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
typeof(studentMajors)
levels(studentMajors)
studentMajors
as.integer(studentMajors)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算

trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
sum(trueInteger)
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(c("1970-01-01 00:02:53", "1980-02-11 11:25:22"))
class(dtObject)
class(dtObjectVector)
```

```{r}
dtObject
as.double(dtObject)
as.double(dtObjectVector)
typeof(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
as.double(twDateTime)
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
as.double(LisbonDateTime)
```

```{r}
twDateTime
LisbonDateTime
```

```{r}
UTCDateTime <- with_tz(twDateTime,tzone = "UTC")
UTCDateTime
```

```{r}
ymd("2018-09-11")
mdy("March,15,19")
```

```{r}
as.integer(ymd("2018-09-11"))
as.integer(mdy("March,15,19"))
```
