---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#7.5
```{r}
Vector1 <- letters [1:6]
Vector1
names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```


```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
```


```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2
```
 

```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
colnames(StuDF2)
StuDF2
```


```{r}
Mat1
names(Mat1) 
```

```{r}
names(Mat1) <- letters[1:6]
names(Mat1)
```

```{r}
matObj1
```


```{r}
colnames(matObj1) <-c('欄位1','欄位2','欄位3')
colnames(matObj1)
matObj1
```

```{r}
rownames(matObj1) <- c('行：1','行：2','行：3','行：4','行：5')
matObj1
```

```{r}
matObj1[c(3,5),c(1,3)]
```


#7.6
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(元素1=1,元素2="Hello",元素3=TRUE)
b
```

```{r}
b$元素3 <- FALSE
b[[5]] <- 7
b
```

```{r}
b[[2]] <- "Hi"
b
b$新成員 <- c(2L,5L,1L)
b
class(b$新成員)
```

```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",col_types = cols(匯率 = col_number(),期間 = col_character()))
```

```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```

```{r}
Logic <- (exData3$期間 >= ymd("1997-06-01") & exData3$期間 <= ymd("1998-12-01"))
Logic
```

```{r}
exData3$isAsiaCrisis <- Logic
exData3
```

```{r}
exData3[exData3$isAsiaCrisis==T,]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
a <- transcriptDataFinal$學號=="92aS67fee" 
transcriptDataFinal[a,]
```

#8.1
```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
class(utility_cobb_douglass)
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8) -> utilityValue
```

```{r}
supply_fun<- function(a,b,P){
  Qs<-a+b*P
  return(Qs) 
}
supply_fun(2,4,5)
demand_fun<- function(c,d,P){
  Qd<-c-d*P
  return(Qd) 
}
demand_fun(5,1,6)
```

```{r}
zoefunction <- function(z,o,e){
  zoe <- z*o-e
return(zoe)
  }
zoefunction(2,4,3)
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
GPA
```

