---
title: '2019-03-27'
author: "林茂廷"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject
```
```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```
```{r}
ParisDateTime <- with_tz(twDateTime,tzone = "Europe/Paris")
ParisDateTime
```
```{r}
NewYorkDateTime <- with_tz(twDateTime,tzone = "America/New_York")
NewYorkDateTime
```

```{r}
typeof(twDateTime)
as.double(twDateTime)
as.integer(twDateTime)
as.double(LisbonDateTime)
```

```{r}
mdy_hms("3-14-2019 8:18:47")
```

```{r}
dmy_hm("27/3/2019 15:56")
```

```{r}
ymd("2018/09/11")
mdy("March 3 2019")
```

```{r}
as.integer(ymd("1970-01-01")) 
as.integer(ymd("1970-01-02")) 
as.integer(ymd("2019-03-11")) 
```

```{r}
Object0<-ymd("2017-04-11")
Object0 
Object1<-mdy("March 27, 2019")
Object1
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```

```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
a + bL
aL + bL
class(a + bL)
class(aL + bL)
a * b
a * bL
aL - bL
class(a * b)
class(a * bL)
class(aL - bL)
```

```{r}
c <- 4

c+a
class(c)
```
```{r}
a^b
a**b
a %% b
aL^bL
a %% bL
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime1 <- ymd_hms("2019-03-27 16:24:00", tz="Asia/Taipei")
twDateTime2 <- ymd_hms("2019-03-20 12:33:00", tz="Asia/Taipei")
twDateTime-twDateTime1
twDateTime1-twDateTime2
class(twDateTime1-twDateTime2)
```

```{r}
DT0 <- ymd("2019-08-11")
DT1 <- ymd("2000-02-01")
DT0-DT1
class(DT0-DT1)
```
```{r}
startingDate <- ymd("2000-02-17")
```

```{r}
startingDate + years(1)
```

```{r}
startingDate + dyears(1)
```

```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```

```{r}
x <- 5
y <- 7
```

```{r}
x < y
x > y
x==y
```

```{r}
x2 <- c(1,5,10)
y2 <-c(-1,5,20)
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3 == y3
x3 != y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
is.na(x2)
```

